- name: Verify that required parameters are set
  assert:
    that:
        - smb_mount_src is defined
        - smb_mount_src | length > 0
        - smb_mount_dest is defined
        - smb_mount_dest | length > 0
  when: ansible_version.string is version('2.11.1', '<')

- name: Verify that user and password are set (non-guest mode)
  assert:
    that:
      - smb_mount_username is defined
      - smb_mount_username | length > 0
      - smb_mount_password is defined
      - smb_mount_password | length > 0
