---
# tasks file for smb_mount
- include: check.yml

- name: Requirements are installed
  package:
    name: cifs-utils

- name: Mount directory is present
  file:
    path: "{{ smb_mount_dest }}"
    owner: "{{ smb_mount_uid }}"
    group: "{{ smb_mount_gid }}"
    mode: "750"
    state: directory

- name: Mount unit is present
  template:
    src: smb-mount.j2
    dest: "/etc/systemd/system/{{ smb_mount_dest | trim(chars='/') | replace('/', '-') }}.mount"
    owner: root
    group: root
    mode: "640"
  notify: restart mount

- name: Mount unit is enabled and running
  systemd:
    name: "{{ smb_mount_dest | trim(chars='/') | replace('/', '-') }}.mount"
    state: started
    enabled: yes
    daemon_reload: yes
