---
# tasks file for smb_mount
- include: check.yml

- name: Requirements are installed
  package:
    name: cifs-utils

- name: Look for minimal virtual kernel # noqa risky-shell-pipe
  shell: dpkg -l | grep linux-image-virtual || true
  changed_when: no
  check_mode: no
  register: smb_virtual_kernel

- name: Extra linux kernel image package is installed
  package:
    name: linux-image-extra-virtual
  when: smb_virtual_kernel.stdout
  register: smb_kernel_package_install

- name: Reboot host to use new kernel # noqa no-handler
  reboot:
  when:
    - smb_kernel_package_install.changed
    - smb_mount_reboot_for_kernel

- name: Mount directory is present
  file:
    path: "{{ smb_mount_dest }}"
    owner: "{{ smb_mount_uid }}"
    group: "{{ smb_mount_gid }}"
    mode: "750"
    state: directory

- name: Mount unit is present
  template:
    src: smb-mount.j2
    dest: "/etc/systemd/system/{{ smb_mount_dest | trim(chars='/') | replace('/', '-') }}.mount"
    owner: root
    group: root
    mode: "640"
  notify: restart mount

- name: Mount unit is enabled and running
  systemd:
    name: "{{ smb_mount_dest | trim(chars='/') | replace('/', '-') }}.mount"
    state: started
    enabled: yes
    daemon_reload: yes
